version: "2"
services:
  identifier:
    image: semtech/mu-identifier:1.0.0
    links:
      - dispatcher:dispatcher
    ports:
      - "80:80"
  dispatcher:
    image: semtech/mu-dispatcher:1.0.1
    links:
      - resourcecache:resourcecache
    volumes:
      - ./config/dispatcher:/config
  db:
    image: tenforce/virtuoso:1.0.0-virtuoso7.2.0
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
  resourcecache:
    image: mu-cache
    environment:
      CACHE_BACKEND: "http://resource/"
    links:
      - resource:resource 
  resource:
    image: semtech/mu-cl-resources:1.10.1
    links:
      - db:database
    volumes:
      - ./config/resources:/config
