version: "2"
services:
  mujs:
    image: mu-javascript-template
  identifier:
    image: semtech/mu-identifier:1.0.0
    links:
      - dispatcher:dispatcher
    ports:
      - "80:80"
  dispatcher:
    image: semtech/mu-dispatcher:1.0.1
    links:
      - resource:resource
      - mujs:mujs
    volumes:
      - ./config/dispatcher:/config
  db:
    image: tenforce/virtuoso:1.0.0-virtuoso7.2.0
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
  resource:
    image: semtech/mu-cl-resources:1.10.1
    links:
      - db:database
    volumes:
      - ./config/resources:/config
